# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LLMs-for-fun',
                'doc_host': 'https://galopyz.github.io',
                'git_url': 'https://github.com/galopyz/LLMs-for-fun',
                'lib_path': 'LLMs_for_fun'},
  'syms': {'LLMs_for_fun.core': {'LLMs_for_fun.core.foo': ('core.html#foo', 'LLMs_for_fun/core.py')}}}
